load("//sdk/rules:defs.bzl", "a53_firmware")

a53_firmware(
    name = "hello_world",
    srcs = [
        "src/helloworld.c",
        "src/platform.c",
        "src/platform.h",
        "src/xuartps_hw.c",
    ],
    bsp = "//sdk/bsp/apu:bsp",
    visibility = ["//visibility:public"],
    deps = ["//sdk/rtos:threadx_a53"],
)
