"""Repository rule + module extension: captures the aarch64-none-elf-gcc
prefix from the AARCH64_GCC_BIN environment variable set by the Nix devShell,
and discovers gcc's built-in <system> include search paths.

Bazel re-runs this rule whenever AARCH64_GCC_BIN changes.

Usage (MODULE.bazel):
    aarch64_gcc_ext = use_extension(
        "//toolchains/aarch64_none_elf:env_ext.bzl",
        "aarch64_gcc_config_ext",
    )
    use_repo(aarch64_gcc_ext, "aarch64_gcc_config")

Consumers (toolchains/aarch64_none_elf/config.bzl):
    load("@aarch64_gcc_config//:defs.bzl",
         "AARCH64_GCC_BIN", "AARCH64_GCC_INCLUDE_DIRS")
"""

# The BSP is committed in-tree at third_party/xilinx_bsp/. Its absolute path
# is discovered from repo_ctx.workspace_root at fetch time and baked into
# defs.bzl so cc_toolchain_config can pass -specs= and -L flags.
_BSP_REL = "third_party/xilinx_bsp"

def _discover_include_dirs(repo_ctx, gcc):
    """Query gcc for its built-in include search paths."""
    r = repo_ctx.execute(
        [gcc, "-E", "-x", "c", "/dev/null", "-v"],
        quiet = True,
    )
    dirs = []
    in_block = False
    for line in r.stderr.splitlines():
        if "#include <...> search starts here" in line:
            in_block = True
            continue
        if "End of search list" in line:
            break
        if in_block:
            d = line.strip()
            if d and "(framework directory)" not in d:
                dirs.append(d)
    return dirs

def _aarch64_gcc_config_impl(repo_ctx):
    gcc_bin = repo_ctx.os.environ.get("AARCH64_GCC_BIN", "").strip()
    if not gcc_bin:
        # Fallback: search PATH so the repo rule succeeds outside the devShell
        # (build actions will fail later if gcc really is missing).
        r = repo_ctx.execute([
            "sh",
            "-c",
            "dirname $(which aarch64-none-elf-gcc 2>/dev/null) 2>/dev/null",
        ])
        gcc_bin = r.stdout.strip() if r.return_code == 0 else ""
    if not gcc_bin:
        gcc_bin = "/usr/bin"  # last resort; keep repo rule non-fatal

    gcc = gcc_bin + "/aarch64-none-elf-gcc"
    include_dirs = _discover_include_dirs(repo_ctx, gcc)

    workspace_root = str(repo_ctx.workspace_root)
    bsp_root = workspace_root + "/" + _BSP_REL

    repo_ctx.file("BUILD.bazel", "# auto-generated by env_ext.bzl\n")
    repo_ctx.file("defs.bzl", """\
# Auto-generated by //toolchains/aarch64_none_elf:env_ext.bzl.
# Re-generated when AARCH64_GCC_BIN changes.

AARCH64_GCC_BIN = {gcc_bin}
AARCH64_GCC_INCLUDE_DIRS = {include_dirs}

# Xilinx ZynqMP BSP paths (committed in the repo).
BSP_SPEC    = {bsp_spec}
BSP_LIB_DIR = {bsp_lib}
""".format(
        gcc_bin = repr(gcc_bin),
        include_dirs = repr(include_dirs),
        bsp_spec = repr(bsp_root + "/Xilinx.spec"),
        bsp_lib = repr(bsp_root + "/lib"),
    ))

_aarch64_gcc_config_rule = repository_rule(
    implementation = _aarch64_gcc_config_impl,
    environ = ["AARCH64_GCC_BIN"],
    local = True,
    doc = "Captures the Nix-provided aarch64-none-elf-gcc path.",
)

def _aarch64_gcc_config_ext_impl(module_ctx):
    _aarch64_gcc_config_rule(name = "aarch64_gcc_config")

aarch64_gcc_config_ext = module_extension(
    implementation = _aarch64_gcc_config_ext_impl,
    environ = ["AARCH64_GCC_BIN"],
)
