"""Repository rule + module extension: captures the arm-none-eabi-gcc prefix
from the ARM_GCC_BIN environment variable set by the Nix devShell, and
discovers gcc's built-in <system> include search paths.

Bazel re-runs this rule whenever ARM_GCC_BIN changes.

Usage (MODULE.bazel):
    arm_gcc_ext = use_extension(
        "//toolchains/arm_none_eabi:env_ext.bzl",
        "arm_gcc_config_ext",
    )
    use_repo(arm_gcc_ext, "arm_gcc_config")

Consumers (toolchains/arm_none_eabi/config.bzl):
    load("@arm_gcc_config//:defs.bzl", "ARM_GCC_BIN", "ARM_GCC_INCLUDE_DIRS")
"""

# Cortex-R5F CPU flags used when discovering the multilib-specific include
# directories (armv7-r hard-float uses a different newlib subdir than the
# default arm7tdmi soft-float multilib).
_CPU_FLAGS = [
    "-mcpu=cortex-r5",
    "-mfpu=vfpv3-d16",
    "-mfloat-abi=hard",
    "-marm",
]

def _discover_include_dirs(repo_ctx, gcc):
    """Query gcc for its built-in include search paths."""
    r = repo_ctx.execute(
        [gcc, "-E", "-x", "c", "/dev/null", "-v"] + _CPU_FLAGS,
        quiet = True,
    )
    dirs = []
    in_block = False
    for line in r.stderr.splitlines():
        if "#include <...> search starts here" in line:
            in_block = True
            continue
        if "End of search list" in line:
            break
        if in_block:
            d = line.strip()
            if d:
                dirs.append(d)
    return dirs

def _arm_gcc_config_impl(repo_ctx):
    gcc_bin = repo_ctx.os.environ.get("ARM_GCC_BIN", "").strip()
    if not gcc_bin:
        r = repo_ctx.execute([
            "sh", "-c",
            "dirname $(which arm-none-eabi-gcc 2>/dev/null) 2>/dev/null",
        ])
        gcc_bin = r.stdout.strip() if r.return_code == 0 else "/usr/bin"

    gcc = gcc_bin + "/arm-none-eabi-gcc"
    include_dirs = _discover_include_dirs(repo_ctx, gcc)

    repo_ctx.file("BUILD.bazel", "# auto-generated by env_ext.bzl\n")
    repo_ctx.file("defs.bzl", """\
# Auto-generated by //toolchains/arm_none_eabi:env_ext.bzl.
# Re-generated when ARM_GCC_BIN changes.

ARM_GCC_BIN = {gcc_bin}
ARM_GCC_INCLUDE_DIRS = {include_dirs}
""".format(gcc_bin = repr(gcc_bin), include_dirs = repr(include_dirs)))

_arm_gcc_config_rule = repository_rule(
    implementation = _arm_gcc_config_impl,
    environ = ["ARM_GCC_BIN"],
    local = True,
    doc = "Captures the Nix-provided arm-none-eabi-gcc path.",
)

def _arm_gcc_config_ext_impl(module_ctx):
    _arm_gcc_config_rule(name = "arm_gcc_config")

arm_gcc_config_ext = module_extension(
    implementation = _arm_gcc_config_ext_impl,
    environ = ["ARM_GCC_BIN"],
)
