// Generated by //orbtrace/model:orbtrace gen-registers; do not edit.
`ifndef ORBTRACE_REGS_SVH
`define ORBTRACE_REGS_SVH
localparam logic [15:0] ORBTRACE_REG_ID = 16'h0000;
localparam logic [15:0] ORBTRACE_REG_VERSION = 16'h0004;
localparam logic [15:0] ORBTRACE_REG_CONTROL = 16'h0008;
localparam logic [15:0] ORBTRACE_REG_SOURCE_FORMAT = 16'h000c;
localparam logic [15:0] ORBTRACE_REG_SWO_BAUD = 16'h0010;
localparam logic [15:0] ORBTRACE_REG_DMA_BASE_LO = 16'h0018;
localparam logic [15:0] ORBTRACE_REG_DMA_BASE_HI = 16'h001c;
localparam logic [15:0] ORBTRACE_REG_DMA_RING_SIZE = 16'h0020;
localparam logic [15:0] ORBTRACE_REG_IRQ_STATUS = 16'h0024;
localparam logic [15:0] ORBTRACE_REG_IRQ_ENABLE = 16'h0028;
localparam logic [15:0] ORBTRACE_REG_RX_BYTES_LO = 16'h0040;
localparam logic [15:0] ORBTRACE_REG_RX_BYTES_HI = 16'h0044;
localparam logic [15:0] ORBTRACE_REG_DROP_BYTES_LO = 16'h0048;
localparam logic [15:0] ORBTRACE_REG_DROP_BYTES_HI = 16'h004c;
localparam logic [15:0] ORBTRACE_REG_SYNC_LOSS_LO = 16'h0050;
localparam logic [15:0] ORBTRACE_REG_SYNC_LOSS_HI = 16'h0054;
localparam logic [15:0] ORBTRACE_REG_FIFO_HIGH_WATER = 16'h0058;
localparam logic [15:0] ORBTRACE_REG_DMA_FAULTS_LO = 16'h0060;
localparam logic [15:0] ORBTRACE_REG_DMA_FAULTS_HI = 16'h0064;
localparam logic [15:0] ORBTRACE_REG_DAP_COMMAND = 16'h0080;
localparam logic [15:0] ORBTRACE_REG_DAP_RESPONSE = 16'h0084;
localparam logic [15:0] ORBTRACE_REG_DAP_STATUS = 16'h0088;
localparam logic [15:0] ORBTRACE_REG_DAP_CONTROL = 16'h008c;
localparam logic [15:0] ORBTRACE_REG_DAP_TRANSFERS_LO = 16'h0090;
localparam logic [15:0] ORBTRACE_REG_DAP_TRANSFERS_HI = 16'h0094;
localparam logic [15:0] ORBTRACE_REG_DAP_ABORTS = 16'h0098;
`endif
